# Data Preprocessing

## Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the Dataset

In [2]:
dataset = pd.read_csv('train.csv')
X_df = dataset[['record_number', 'days_since_opened', 'days_since_confirmed', 'primary_term', 'final_term', 'days_till_primary_close', 'days_till_final_close', 'loans_credit_limit', 'loans_next_payment_summary', 'loans_outstanding_balance', 'loans_credit_cost_rate', 'utilization', 'max_over_limit_count', 'encoded_payment_0', 'encoded_payment_1', 'encoded_payment_2', 'encoded_payment_4', 'encoded_payment_5', 'encoded_payment_6', 'encoded_payment_7', 'encoded_payment_8', 'encoded_payment_14', 'encoded_loans_account_holder_type', 'encoded_loans_credit_status', 'encoded_loans_credit_type']]
X = X_df.values
y1 = dataset.iloc[:, 60].values
y2 = dataset.iloc[:, 61].values

In [3]:
dataset.describe()

record_number  days_since_opened  days_since_confirmed  primary_term  \
count   1.106674e+06       1.106674e+06          1.106674e+06  1.106674e+06   
mean    9.149727e+00       9.433967e+00          8.231377e+00  8.408147e+00   
std     5.746106e+00       5.747728e+00          4.776280e+00  5.282007e+00   
min     1.000000e+00       0.000000e+00          0.000000e+00  0.000000e+00   
25%     5.000000e+00       5.000000e+00          4.000000e+00  4.000000e+00   
50%     9.000000e+00       1.000000e+01          9.000000e+00  8.000000e+00   
75%     1.300000e+01       1.400000e+01          1.200000e+01  1.400000e+01   
max     4.700000e+01       1.900000e+01          1.700000e+01  1.700000e+01   

         final_term  days_till_primary_close  days_till_final_close  \
count  1.106674e+06             1.106674e+06           1.106674e+06   
mean   8.282763e+00             7.273099e+00           8.193988e+00   
std    4.565543e+00             5.094787e+00           4.321941e+00   
min    0.000000e+00             0.000000e+00           0.000000e+00   
25%    5.000000e+00             2.000000e+00           5.000000e+00   
50%    8.000000e+00             7.000000e+00           9.000000e+00   
75%    1.200000e+01             1.200000e+01           1.100000e+01   
max    1.600000e+01             1.600000e+01           1.500000e+01   

       loans_credit_limit  loans_next_payment_summary  \
count        1.106674e+06                1.106674e+06   
mean         9.715922e+00                2.332612e+00   
std          5.844795e+00                1.247430e+00   
min          0.000000e+00                0.000000e+00   
25%          5.000000e+00                2.000000e+00   
50%          1.000000e+01                2.000000e+00   
75%          1.500000e+01                2.000000e+00   
max          1.900000e+01                6.000000e+00   

       loans_outstanding_balance  ...  encoded_payment_21  encoded_payment_22  \
count               1.106674e+06  ...        1.069126e+06        1.069519e+06   
mean                2.993031e+00  ...        2.328069e+00        2.359353e+00   
std                 6.411320e-01  ...        1.238293e+00        1.217475e+00   
min                 1.000000e+00  ...        0.000000e+00        0.000000e+00   
25%                 3.000000e+00  ...        3.000000e+00        3.000000e+00   
50%                 3.000000e+00  ...        3.000000e+00        3.000000e+00   
75%                 3.000000e+00  ...        3.000000e+00        3.000000e+00   
max                 5.000000e+00  ...        3.000000e+00        3.000000e+00   

       encoded_payment_23  encoded_payment_24  \
count        1.070131e+06        1.070629e+06   
mean         2.393023e+00        3.529236e+00   
std          1.193804e+00        1.081633e+00   
min          0.000000e+00        1.000000e+00   
25%          3.000000e+00        4.000000e+00   
50%          3.000000e+00        4.000000e+00   
75%          3.000000e+00        4.000000e+00   
max          3.000000e+00        4.000000e+00   

       encoded_loans_account_holder_type  encoded_loans_credit_status  \
count                       1.106674e+06                 1.106674e+06   
mean                        1.029407e+00                 2.758336e+00   
std                         2.931483e-01                 4.686307e-01   
min                         0.000000e+00                 0.000000e+00   
25%                         1.000000e+00                 2.000000e+00   
50%                         1.000000e+00                 3.000000e+00   
75%                         1.000000e+00                 3.000000e+00   
max                         6.000000e+00                 6.000000e+00   

       encoded_loans_credit_type  encoded_loans_account_currency  \
count               1.106674e+06                    1.106674e+06   
mean                3.599215e+00                    1.001480e+00   
std                 1.011067e+00                    4.470347e-02   
min                 0.000000e+00       

In [4]:
X

array([[ 7., 10.,  8., ...,  1.,  3.,  4.],
       [ 5., 15.,  6., ...,  1.,  3.,  4.],
       [ 1., 15., 17., ...,  1.,  3.,  4.],
       ...,
       [ 3.,  8.,  7., ...,  1.,  3.,  4.],
       [ 4., 10.,  4., ...,  1.,  3.,  4.],
       [12.,  1., 10., ...,  1.,  2.,  3.]])

In [5]:
len(X[1])

25

## Taking care of missing values

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer.fit(X[:, :])
X[:, :] = imputer.transform(X[:, :])

## Splitting the dataset

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size = 0.2, random_state = 1)
X_train, X_test, y2_train, y2_test = train_test_split(X, y2, test_size = 0.2, random_state = 1)

# Training Descision Tree classifier for y1

In [8]:
from sklearn.tree import DecisionTreeClassifier
classifierY1 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierY1.fit(X_train, y1_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [9]:
y1_pred = classifierY1.predict(X_test)
print(np.concatenate((y1_pred.reshape(len(y1_pred),1), y1_test.reshape(len(y1_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Accuracy and confusion matrix

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y1_test, y1_pred)
print(cm)
accuracy_score(y1_test, y1_pred)

[[193095     11]
 [    15  28214]]


0.9998825310050377

In [11]:
roc_auc_score(y1_test, y1_pred)

0.9997058340080671

# Training descision tree classifier for y2

In [12]:
from sklearn.tree import DecisionTreeClassifier
classifierY2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifierY2.fit(X_train, y2_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [13]:
y2_pred = classifierY2.predict(X_test)
print(np.concatenate((y2_pred.reshape(len(y2_pred),1), y2_test.reshape(len(y2_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Accuracy and confusion matrix

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score
cm = confusion_matrix(y2_test, y2_pred)
print(cm)
accuracy_score(y2_test, y2_pred)

[[179153      3]
 [     2  42177]]


0.9999774098086611

In [15]:
roc_auc_score(y2_test, y2_pred)

0.9999679189279921

# Finding the result on Test data

In [16]:
dataset_test = pd.read_csv('test.csv')
dataset_test_df = dataset_test[['record_number', 'days_since_opened', 'days_since_confirmed', 'primary_term', 'final_term', 'days_till_primary_close', 'days_till_final_close', 'loans_credit_limit', 'loans_next_payment_summary', 'loans_outstanding_balance', 'loans_credit_cost_rate', 'utilization', 'max_over_limit_count', 'encoded_payment_0', 'encoded_payment_1', 'encoded_payment_2', 'encoded_payment_4', 'encoded_payment_5', 'encoded_payment_6', 'encoded_payment_7', 'encoded_payment_8', 'encoded_payment_14', 'encoded_loans_account_holder_type', 'encoded_loans_credit_status', 'encoded_loans_credit_type']]
X_test = dataset_test_df.values

In [17]:
dataset_test.describe()

record_number  days_since_opened  days_since_confirmed   primary_term  \
count  474289.000000      474289.000000         474289.000000  474289.000000   
mean        9.158857           9.429103              8.244627       8.414821   
std         5.757169           5.748442              4.780351       5.282216   
min         1.000000           0.000000              0.000000       0.000000   
25%         5.000000           5.000000              4.000000       4.000000   
50%         9.000000          10.000000              9.000000       8.000000   
75%        13.000000          14.000000             12.000000      14.000000   
max        48.000000          19.000000             17.000000      17.000000   

          final_term  days_till_primary_close  days_till_final_close  \
count  474289.000000            474289.000000          474289.000000   
mean        8.272642                 7.279222               8.204736   
std         4.561479                 5.103062               4.319350   
min         0.000000                 0.000000               0.000000   
25%         5.000000                 2.000000               5.000000   
50%         8.000000                 7.000000               9.000000   
75%        12.000000                12.000000              11.000000   
max        16.000000                16.000000              15.000000   

       loans_credit_limit  loans_next_payment_summary  \
count       474289.000000               474289.000000   
mean             9.710535                    2.329729   
std              5.845884                    1.244149   
min              0.000000                    0.000000   
25%              5.000000                    2.000000   
50%             10.000000                    2.000000   
75%             15.000000                    2.000000   
max             19.000000                    6.000000   

       loans_outstanding_balance  ...  encoded_payment_19  encoded_payment_20  \
count              474289.000000  ...       458580.000000       458035.000000   
mean                    2.992034  ...            2.262318            3.297436   
std                     0.639825  ...            1.278726            1.257742   
min                     1.000000  ...            0.000000            1.000000   
25%                     3.000000  ...            1.000000            4.000000   
50%                     3.000000  ...            3.000000            4.000000   
75%                     3.000000  ...            3.000000            4.000000   
max                     5.000000  ...            3.000000            4.000000   

       encoded_payment_21  encoded_payment_22  encoded_payment_23  \
count       458386.000000        458579.00000       458777.000000   
mean             2.328782             2.36083            2.394734   
std              1.237950             1.21678            1.192558   
min              0.000000             0.00000            0.000000   
25%              3.000000             3.00000            3.000000   
50%              3.000000             3.00000            3.000000   
75%              3.000000             3.00000            3.000000   
max              3.000000             3.00000            3.000000   

       encoded_payment_24  encoded_loans_account_holder_type  \
count       458908.000000                      474289.000000   
mean             3.528960                           1.029859   
std              1.082126                           0.294979   
min              1.000000                           1.000000   
25%              4.000000                           1.000000   
50%              4.000000                           1.000000   
75%              4.000000                           1.000000   
max              4.000000                           6.000000   

       encoded_loans_credit_status  encoded_loans_credit_type  \
count                474289.000000              474289.000000   
mean                      2.757401                   3.596527   

In [18]:
dataset_test.head()

customer_id firstname lastname  record_number  \
0  1dffd171-010b-4773-894f-4095077b0e31   Aradhya     Deep             14   
1  cf0e7f8c-b22b-410c-8ad6-4a5bfd4d11cf   Anahita    Anand             17   
2  49c9f6ef-58f2-4334-bb44-9a4ded2e587f     Amani      Tak             14   
3  daab9520-7716-4b1e-b791-907912a81f79    Tushar    Sodhi              7   
4  9d4adc34-368e-4642-98a2-58d73b4294f7    Jivika     Rana             13   

   days_since_opened  days_since_confirmed  primary_term  final_term  \
0                  2                    13            14           2   
1                  3                     6             0           1   
2                  9                    10            14           7   
3                 14                     4            12          11   
4                  3                     3            16           1   

   days_till_primary_close  days_till_final_close  ...  encoded_payment_19  \
0                       14                      6  ...                 3.0   
1                        0                      4  ...                 0.0   
2                       10                      4  ...                 3.0   
3                        6                     13  ...                 3.0   
4                       15                      4  ...                 3.0   

   encoded_payment_20  encoded_payment_21  encoded_payment_22  \
0                 4.0                 3.0                 3.0   
1                 1.0                 0.0                 0.0   
2                 4.0                 3.0                 3.0   
3                 4.0                 3.0                 3.0   
4                 4.0                 3.0                 3.0   

   encoded_payment_23  encoded_payment_24  encoded_loans_account_holder_type  \
0                 3.0                 NaN                                  1   
1                 0.0                 1.0                                  1   
2                 3.0                 4.0                                  1   
3                 3.0                 4.0                                  1   
4                 3.0                 4.0                                  1   

   encoded_loans_credit_status  encoded_loans_credit_type  \
0                            3                          4   
1                            2                          3   
2                            2                          4   
3                            3                          4   
4                            3                          3   

   encoded_loans_account_currency  
0                               1  
1                               1  
2                               1  
3                               1  
4                               1  

[5 rows x 60 columns]

In [19]:
dataset_test_df.head()

record_number  days_since_opened  days_since_confirmed  primary_term  \
0             14                  2                    13            14   
1             17                  3                     6             0   
2             14                  9                    10            14   
3              7                 14                     4            12   
4             13                  3                     3            16   

   final_term  days_till_primary_close  days_till_final_close  \
0           2                       14                      6   
1           1                        0                      4   
2           7                       10                      4   
3          11                        6                     13   
4           1                       15                      4   

   loans_credit_limit  loans_next_payment_summary  loans_outstanding_balance  \
0                   1                           2                          3   
1                   8                           2                          4   
2                   2                           5                          1   
3                  11                           2                          3   
4                  16                           2                          3   

   ...  encoded_payment_2  encoded_payment_4  encoded_payment_5  \
0  ...                0.0                0.0                0.0   
1  ...                NaN                0.0                0.0   
2  ...                0.0                0.0                0.0   
3  ...                0.0                0.0                NaN   
4  ...                0.0                0.0                0.0   

   encoded_payment_6  encoded_payment_7  encoded_payment_8  \
0                0.0                0.0                0.0   
1                0.0                0.0                0.0   
2                0.0                0.0                0.0   
3                3.0                3.0                3.0   
4                0.0                0.0                0.0   

   encoded_payment_14  encoded_loans_account_holder_type  \
0                 3.0                                  1   
1                 0.0                                  1   
2                 3.0                                  1   
3                 3.0                                  1   
4                 0.0                                  1   

   encoded_loans_credit_status  encoded_loans_credit_type  
0                            3                          4  
1                            2                          3  
2                            2                          4  
3                            3                          4  
4                            3                          3  

[5 rows x 25 columns]

In [20]:
X_test

array([[14.,  2., 13., ...,  1.,  3.,  4.],
       [17.,  3.,  6., ...,  1.,  2.,  3.],
       [14.,  9., 10., ...,  1.,  2.,  4.],
       ...,
       [12.,  6., 13., ...,  1.,  3.,  4.],
       [16.,  2., 16., ...,  1.,  2.,  3.],
       [ 8., 10., 14., ...,  1.,  3.,  4.]])

In [21]:
len(X_test[0])

25

## Taking Care of missing values

In [22]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy= 'median')
imputer.fit(X_test[:, :])
X_test[:, :] = imputer.transform(X_test[:, :])

## Predicting Y1 -> Primary Close Flag

In [23]:
y1_pred = classifierY1.predict(X_test)

In [24]:
print(y1_pred)

[0 0 0 ... 0 0 0]


## Predicting Y2 -> Final Close Flag

In [25]:
y2_pred = classifierY2.predict(X_test)

In [26]:
print(y2_pred)

[0 0 0 ... 0 0 0]


In [27]:
len(y2_pred)

474289

In [28]:
result_array = np.concatenate((y1_pred.reshape(len(y1_pred),1), y2_pred.reshape(len(y2_pred),1)),1)

In [29]:
print(result_array)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [30]:
print(result_array)

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [31]:
print(len(result_array))

474289


In [32]:
print(result_array[474288])

[0 0]


In [33]:
print(result_array[19])

[1 1]


In [34]:
submission_df = pd.DataFrame(result_array)

In [35]:
submission_df.to_csv('submission.csv',index=False )